package main

import "database/sql"

const schema = `
CREATE TABLE IF NOT EXISTS Categoria (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Nombre TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Producto (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Nombre TEXT NOT NULL,
    CategoriaID INTEGER NOT NULL,
    Precio REAL NOT NULL,
    Stock INTEGER NOT NULL,
    CodigoBarras TEXT,
    FOREIGN KEY (CategoriaID) REFERENCES Categoria(ID)
);

CREATE TABLE IF NOT EXISTS Boleta (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Fecha DATETIME NOT NULL,
    Total REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS DetalleVenta (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_Producto INTEGER NOT NULL,
    Cant_Producto INTEGER NOT NULL,
    ID_Boleta INTEGER NOT NULL,
    FOREIGN KEY (ID_Producto) REFERENCES Producto(ID),
    FOREIGN KEY (ID_Boleta) REFERENCES Boleta(ID)
);
CREATE TABLE IF NOT EXISTS Usuario (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NombreUsuario TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    Rol TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS Pedido (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Distribuidor TEXT NOT NULL,
    Fecha TEXT NOT NULL,
    FechaEstimada TEXT,
    Estado TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PedidoProducto (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PedidoID INTEGER NOT NULL,
    ProductoID INTEGER NOT NULL,
    Cantidad INTEGER NOT NULL,
    FOREIGN KEY (PedidoID) REFERENCES Pedido(ID),
    FOREIGN KEY (ProductoID) REFERENCES Producto(ID)
);
`

func createTables(database *sql.DB) error {
	_, err := database.Exec(schema)
	return err
}